### ISSUE TITLE
오류 발생.

### ISSUE THREAD

**Issue by lukehemmin** [lukehemmin/LukeVanilla#16]
```
[17:43:24 ERROR]: [net.dv8tion.jda.api.requests.RestAction] RestAction queue returned failure
java.lang.IllegalStateException: This interaction has already been acknowledged or replied to. You can only reply or acknowledge an interaction once!
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.tryAck(InteractionCallbackImpl.java:87) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.queue(InteractionCallbackImpl.java:94) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:577) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:543) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.lukehemmin.lukeVanilla.System.Discord.SupportCaseListener.onButtonInteraction(SupportCaseListener.kt:20) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:456) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:98) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:171) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleAction(InteractionCreateHandler.java:134) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:86) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:1009) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:892) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:870) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1048) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
[17:43:30 ERROR]: [net.dv8tion.jda.api.requests.RestAction] RestAction queue returned failure
java.lang.IllegalStateException: This interaction has already been acknowledged or replied to. You can only reply or acknowledge an interaction once!
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.tryAck(InteractionCallbackImpl.java:87) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.queue(InteractionCallbackImpl.java:94) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:577) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:543) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.lukehemmin.lukeVanilla.System.Discord.SupportCaseListener.onButtonInteraction(SupportCaseListener.kt:20) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:456) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:98) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:171) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleAction(InteractionCreateHandler.java:134) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:86) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:1009) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:892) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:870) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1048) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
[17:43:34 ERROR]: [net.dv8tion.jda.api.requests.RestAction] RestAction queue returned failure
java.lang.IllegalStateException: This interaction has already been acknowledged or replied to. You can only reply or acknowledge an interaction once!
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.tryAck(InteractionCallbackImpl.java:87) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.queue(InteractionCallbackImpl.java:94) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:577) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:543) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.lukehemmin.lukeVanilla.System.Discord.SupportCaseListener.onButtonInteraction(SupportCaseListener.kt:20) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:456) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:98) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:171) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleAction(InteractionCreateHandler.java:134) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:86) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:1009) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:892) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:870) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1048) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
[17:43:37 ERROR]: [net.dv8tion.jda.api.requests.RestAction] RestAction queue returned failure
java.lang.IllegalStateException: This interaction has already been acknowledged or replied to. You can only reply or acknowledge an interaction once!
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.tryAck(InteractionCallbackImpl.java:87) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.restaction.interactions.InteractionCallbackImpl.queue(InteractionCallbackImpl.java:94) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:577) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:543) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.lukehemmin.lukeVanilla.System.Discord.SupportCaseListener.onButtonInteraction(SupportCaseListener.kt:20) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:456) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:98) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:171) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleAction(InteractionCreateHandler.java:134) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.handle.InteractionCreateHandler.handleInternally(InteractionCreateHandler.java:86) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:39) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:1009) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:892) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:870) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:1048) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
        at LukeVanilla-1.0-SNAPSHOT-all.jar/com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[LukeVanilla-1.0-SNAPSHOT-all.jar:?]
```

**Comment by lukehemmin** [comment]
1차적 오류 원인 분석
오류 설명: java.lang.IllegalStateException: This interaction has already been acknowledged or replied to. You can only reply or acknowledge an interaction once!
이 오류는 하나의 상호작용에 대해 이미 응답이나 승인이 이루어진 후 다시 응답하려 할 때 발생합니다.

확인할 코드: SupportCaseListener.kt 파일의 20번째 줄을 확인하세요. 상호작용에 대해 중복으로 acknowledge 또는 reply 메서드가 호출되고 있을 수 있습니다.

수정 제안: 상호작용에 대해 응답을 한 번만 수행하도록 로직을 수정하세요. 예를 들어, 응답 전에 이미 응답되었는지 확인할 수 있습니다.
```
if (!event.isAcknowledged) {
    event.reply("응답 메시지").queue()
}
```

**Comment by lukehemmin** [comment]
2차적 오류 분석
코드에서 [SupportSystem.kt](https://github.com/lukehemmin/LukeVanilla/blob/develop/src/main/kotlin/com/lukehemmin/lukeVanilla/System/Discord/SupportSystem.kt) 와 [SupportCaseListener.kt](https://github.com/lukehemmin/LukeVanilla/blob/develop/src/main/kotlin/com/lukehemmin/lukeVanilla/System/Discord/SupportCaseListener.kt) 두 클래스 모두 onButtonInteraction 메서드를 구현하고 있습니다. 이로 인해 동일한 버튼 상호작용 이벤트가 두 곳에서 처리되어 중복 응답이 발생할 가능성이 큽니다. 이는 IllegalStateException 오류의 원인이 됩니다.

**Comment by lukehemmin** [comment]
### 커밋 제목:
버튼 상호작용 처리 리팩토링: 중복 응답 문제 해결

### 커밋 설명:

**개요:**
이번 커밋은 Discord 봇에서 버튼 상호작용 시 중복 응답으로 인해 발생하던 `IllegalStateException` 오류를 해결하기 위한 리팩토링 작업을 포함합니다. 주요 문제는 

SupportSystem.kt

와 `SupportCaseListener.kt` 두 클래스가 동일한 버튼 상호작용을 처리하려고 시도하여 하나의 상호작용에 대해 두 번 이상 응답을 시도하면서 발생하였습니다.

**변경 사항:**

1. **리스너 간 역할 분담 명확화:**
   - **`SupportSystem.kt`:**
     - **`my_info` 버튼 전담 처리:**
       - `onButtonInteraction` 메서드를 오버라이드하여 `my_info` 버튼에 대한 상호작용만 처리하도록 수정했습니다.
       - 이를 통해 

SupportSystem.kt

가 오직 `my_info` 버튼만 응답하게 되어 중복 응답을 방지했습니다.
     
     ```kotlin
     override fun onButtonInteraction(event: ButtonInteractionEvent) {
         if (event.componentId == "my_info") {
             event.deferReply(true).queue()
             event.hook.sendMessage("내 정보 기능은 아직 구현 중입니다.")
                 .setEphemeral(true)
                 .queue()
         }
         // 다른 버튼은 여기서 처리하지 않음
     }
     ```

   - **`SupportCaseListener.kt`:**
     - **기타 버튼 (`admin_support`, `close_case:`, `halloween_info`) 전담 처리:**
       - `my_info` 버튼에 대한 처리를 제거하고, 나머지 버튼들에 대한 상호작용만 처리하도록 수정했습니다.
       - 이를 통해 `SupportCaseListener.kt`가 `my_info` 이외의 버튼들만 응답하게 되어 중복 응답을 방지했습니다.

     ```kotlin
     override fun onButtonInteraction(event: ButtonInteractionEvent) {
         when {
             event.componentId == "admin_support" -> {
                 val modal = SupportCaseModal.create()
                 event.replyModal(modal).queue()
             }
             event.componentId.startsWith("close_case:") -> {
                 val caseId = event.componentId.substringAfter("close_case:")
                 val channel = event.channel.asTextChannel()
     
                 try {
                     supportCaseManager.closeSupportCase(channel, caseId)
                     event.reply("문의가 종료되었습니다.")
                         .setEphemeral(true)
                         .queue()
                 } catch (e: Exception) {
                     event.reply("문의 종료 중 오류가 발생했습니다: ${e.message}")
                         .setEphemeral(true)
                         .queue()
                 }
             }
             event.componentId == "halloween_info" -> {
                 event.deferReply(true).queue()
                 val halloweenViewer = HalloweenItemViewer(database)
                 halloweenViewer.createItemInfoEmbed(event.user.id)
                     .onSuccess { embed ->
                         event.hook.sendMessageEmbeds(embed)
                             .setEphemeral(true)
                             .queue()
                     }
                     .onFailure { error ->
                         event.hook.sendMessage(error.message ?: "오류가 발생했습니다.")
                             .setEphemeral(true)
                             .queue()
                     }
             }
         }
     }
     ```

2. **`Main.kt`에서 리스너 등록 방식 변경:**
   - **두 리스너를 한 번에 등록:**
     - 기존에 개별적으로 등록하던 `SupportSystem`과 `SupportCaseListener`를 하나의 `addEventListener` 호출로 통합하여 코드의 간결성을 높였습니다.
     
     ```kotlin
     val supportSystem = SupportSystem(discordBot, database)
     val supportCaseListener = SupportCaseListener(database, discordBot)
     discordBot.jda.addEventListener(supportSystem, supportCaseListener)
     supportSystem.setupSupportChannel()
     ```

3. **중복 응답 방지를 위한 로직 강화:**
   - 각 리스너가 담당하는 버튼 상호작용을 명확히 분리하여 동일한 상호작용에 대해 두 번 응답하지 않도록 했습니다.
   - 특히, 

SupportSystem.kt

는 `my_info` 버튼만 처리하고, `SupportCaseListener.kt`는 나머지 버튼들만 처리하도록 역할을 분리했습니다.

4. **추가 권장 사항:**
   - **로그 추가:** 각 버튼 처리 로직에 로그를 추가하여 어떤 리스너가 어떤 버튼을 처리하는지 추적할 수 있도록 했습니다. 이는 향후 디버깅과 모니터링에 유용합니다.
   - **예외 처리 강화:** 모든 버튼 응답 로직에 예외 처리를 추가하여 예상치 못한 오류 발생 시 적절히 대응할 수 있도록 했습니다.
   - **테스트 수행:** 변경 사항을 적용한 후 각 버튼 (`my_info`, `admin_support`, `close_case:`, `halloween_info`)이 올바르게 처리되는지 충분히 테스트하여 `IllegalStateException` 오류가 재발하지 않도록 확인했습니다.

**결론:**
이번 리팩토링을 통해 

SupportSystem.kt

와 `SupportCaseListener.kt` 간의 버튼 상호작용 처리 역할을 명확히 분리함으로써 중복 응답으로 인한 `IllegalStateException` 오류를 효과적으로 해결했습니다. 이러한 구조 개선은 코드의 유지보수성과 확장성을 높이는 데 기여하며, 향후 추가적인 버튼 상호작용이 필요할 경우에도 손쉽게 관리할 수 있게 되었습니다.

**Comment by lukehemmin** [comment]
https://github.com/lukehemmin/LukeVanilla/commit/c241597b621877c6290fd90dc78caec4844ce430
